version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566-4599:4566-4599'
    environment:
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"